### ISSUE TITLE
Do any of the glTF-Sample-Models work ?

### ISSUE THREAD

**Issue by mslinklater** [PacktPublishing/Mastering-Graphics-Programming-with-Vulkan#14]
I've tried a few of the glTF-Sample-Models with Chapter 1 and none of them render anything. I get the two windows rendering fine but no model... it's just a green background. I've tried Box, Cube. Suzanne... all load without error but don't actually render anything. Am I doing something wrong ?

**Comment by theWatchmen** [comment]
I think I know what this is: we hardcoded the model scale for Sponza, so most of the other models are too small to be seen. You can change the scale in the code or from the UI. We do the right thing in the next chapters, I'll see how easy it is to port that change to chapter 1.

**Comment by mslinklater** [comment]
Thanks. I've just tried Sponza and it's rendering fine. Good to know it's working 8)

**Comment by theWatchmen** [comment]
I am going to close this issue as it looks like it's been resolved. Feel free to reopen it if needed :)
