### ISSUE TITLE
Raptor Assert uses outdated predefined macro

### ISSUE THREAD

**Issue by drsnuggles8** [PacktPublishing/Mastering-Graphics-Programming-with-Vulkan#15]
In the file assert.hpp, in line 8 it is checked if `_MSV_VER` is defined. I believe this should be a check for `_MSC_VER` instead.

[Link to file](https://github.com/PacktPublishing/Mastering-Graphics-Programming-with-Vulkan/blob/main/source/raptor/foundation/assert.hpp)

**Comment by theWatchmen** [comment]
Thanks for letting us know , this is now fixed.
