### ISSUE TITLE
seems can't compile for aarch64 system

### ISSUE THREAD

**Issue by pengliu916** [PacktPublishing/Mastering-Graphics-Programming-with-Vulkan#16]
Hi there, I really love the book, and really want to try it on nvidia aarch64 device (I have agx orion), and it seems some of the functions in foundation layer need SSE support, could we have a branch without SSE? I have no problem running Vulkan SDK examples, so I am pretty sure with some modification, your Raptor engine should run happily on my agx orion

Thanks

**Comment by theWatchmen** [comment]
Hi, thanks for letting us know. We can take a look, but it might be a while before we sort this out :)

**Comment by pengliu916** [comment]
Cool, it seems the code blocking aarch64 is in hash_map.hpp and it's dependency wyhash.h. wyhash version 4 seems fixed the issue, so just update wyhash would fix it, what left is inside hash_map.hpp where I can see SSE instructions inside the code, maybe protected with some macro and provide a fallback SW route would work. I bet there are decent number of ppl reading this exciting book want to try it on their raspberry pi or jetson machines
