### ISSUE TITLE
Duplicate include in log.hpp

### ISSUE THREAD

**Issue by jsjtxietian** [PacktPublishing/Mastering-Graphics-Programming-with-Vulkan#17]
There are two  **#include "foundation/platform.hpp"** in log.hpp

https://github.com/PacktPublishing/Mastering-Graphics-Programming-with-Vulkan/blob/469d625eda754dfdd7fa0778da352625ed9ccecc/source/raptor/foundation/log.hpp#L3-L4

**Comment by jsjtxietian** [comment]
PR is here #18

**Comment by theWatchmen** [comment]
Thanks for spotting this :) PR has been merged.
