### ISSUE TITLE
Feature: Imgui with multiviewports and docking

### ISSUE THREAD

**Issue by firesgc** [PacktPublishing/Mastering-Graphics-Programming-with-Vulkan#21]
Hello!

Do you have any plans to add support for Imgui with multiviewports and docking? 

It looks like it would be a major structural change. Do you have a tip on how to detach the swapchains from the GPUDevice class and "bind" them to a window? 

Thanks a lot for your awesome project!

**Comment by theWatchmen** [comment]
Thanks for the kind words :) We don't plan to support the docking branch of imgui in the short term, but it's something we might consider down the line. If you wanted to decouple the swapchain from the device, you could treat it like other resources (buffers and images) and use an handle for it. Then you would have to pass it to all the device functions that make use of it.

**Comment by firesgc** [comment]
Thanks for the reply! I will try when I have some time!
