### ISSUE TITLE
Wrong depth image transition (VK_IMAGE_LAYOUT_UNDEFINED -> VK_IMAGE_LAYOUT_PRESENT_SRC_KHR)

### ISSUE THREAD

**Issue by dorian-apanel-intel** [PacktPublishing/Mastering-Graphics-Programming-with-Vulkan#22]
There is a wrong transition of depth image to VK_IMAGE_LAYOUT_PRESENT_SRC_KHR layout.

In following line:
https://github.com/PacktPublishing/Mastering-Graphics-Programming-with-Vulkan/blob/b5f3092c77a331b99f800b3355cba35854047a2a/source/chapter1/graphics/gpu_device.cpp#L1786

Vk Spec states:
`VK_IMAGE_LAYOUT_PRESENT_SRC_KHR must only be used for presenting a presentable image for display`

Validation layers are currently silent about this, but there is already an issue created for it https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4309

**Comment by dorian-apanel-intel** [comment]
This transition is not needed in my opinion. It is done only in initial command buffer, and following render passes do Discard+Clear anyway.
![image](https://user-images.githubusercontent.com/72810961/224037932-72cb9711-03a2-429a-918a-31430e588ffb.png)

![image](https://user-images.githubusercontent.com/72810961/224037992-54c8b3af-2121-4110-8d37-fe647814c270.png)

**Comment by theWatchmen** [comment]
Thanks, I agree this is likely not needed. I merged your changes and then ported the fix to the other chapters.

**Comment by dorian-apanel-intel** [comment]
Thanks :)
