### ISSUE TITLE
Overflow converting values and unable to load other models

### ISSUE THREAD

**Issue by OptimisticMonkey** [PacktPublishing/Mastering-Graphics-Programming-with-Vulkan#24]
When running the default Chapter 1, the console prints an endless stream of:  
Overflow converting values 18446744069414584320, 2147483647
Overflow converting values 18446744069414584320, 2147483647
Overflow converting values 18446744069414584320, 2147483647
Overflow converting values 18446744069414584320, 2147483647
Overflow converting values 18446744069414584320, 2147483647

I think maybe they are validation errors?
The default scene, Sponza does appear, and I can navigate around.

However, trying to load other models, such as Duck,  just shows solid green background.  I tried various zoom levels but cannot see model.

It also prints endless stream of errors.

The gltf files does load fine into unreal.

**Comment by OptimisticMonkey** [comment]
fwiw all the models seem to load fine using https://github.com/SaschaWillems/Vulkan-glTF-PBR as well

Thanks for any advice/help on getting Raptor to work

**Comment by theWatchmen** [comment]
Hi, see #9 for the overflow issue and #14 for the glTF issue. We haven't got around to fix the scaling in the first chapters :)

**Comment by OptimisticMonkey** [comment]
So #9 fixed overflow!  Sadly I couldnt find any scale that would bring the Duck into focus...  but Sponza is working fine.... I will move on to next chapter...

**Comment by shruthis-shetty** [comment]
Hello @theWatchmen and @OptimisticMonkey , I hope we are good to close this issue. Please confirm me.

**Comment by theWatchmen** [comment]
I'll close this. Fixing the glTF load issue will be tracked under #29
