### ISSUE TITLE
RenderDoc cannot capture the application

### ISSUE THREAD

**Issue by omd24** [PacktPublishing/Mastering-Graphics-Programming-with-Vulkan#25]
Not sure if this is a RenderDoc bug or an issue with how vulkan is set up but just trying to take a capture of chapter 2 demo with RenderDoc and it seems it cannot figure out the api. The status window says "Connection Established" and runs the app properly but under the "API" field says "None". As a result the F12 to take captures doesn't work. Also there is no renderdoc overlay on the demo window.

> ![image](https://user-images.githubusercontent.com/74592722/224567626-810b7629-d863-4ad7-bb56-519adbc30b75.png)

**Comment by theWatchmen** [comment]
Interesting, we did have some issue with RenderDoc once we started using mesh shaders, but chapter 2 should work. For Vulkan, the first time you launch RenderDoc you have to register the RenderDoc layer. There should be a message in RenderDoc that asks you to register the layer. I will also try on my machine to make sure it still works on my end.

**Comment by omd24** [comment]
Not sure what was the issue but reinstalling the RenderDoc did the trick ¯\_(ツ)_/¯
