### ISSUE TITLE
Where can we find the assets?

### ISSUE THREAD

**Issue by d13omiresmaeili** [PacktPublishing/Mastering-Graphics-Programming-with-Vulkan#4]
Hi, just wanted to run the chapter 1 sample and it requires some gltf model, where can we get those?

**Comment by d13omiresmaeili** [comment]
For now I got the models from [https://github.com/KhronosGroup/glTF-Sample-Models](https://github.com/KhronosGroup/glTF-Sample-Models) and tested a few of them and so far I can tell the gltf-loading code works fine 🥳

**Comment by theWatchmen** [comment]
We have merged the #2 to make it easier to download the models and run the code :)
