### ISSUE TITLE
Exits directly

### ISSUE THREAD

**Issue by ohmaya** [PacktPublishing/Mastering-Graphics-Programming-with-Vulkan#43]
- Open the .sln with Visual Studio 2022.
- Debug Chapter 1's project.

RaptorEngine_Chapter1_Debug.exe (process 91692) exited with code -1.

**Comment by theWatchmen** [comment]
Thanks for the report. We would a bit more information to understand what's going wrong. Have you run the bootstrap script to download the assets? If not, are you passing a glTF asset path when you start the process?

If you have done the above, could you provide the output of the console log?

**Comment by theWatchmen** [comment]
We haven't received an update on this, closing.

**Comment by ohmaya** [comment]
if ( argc < 2 ) {
        printf( "Usage: chapter1 [path to glTF model]\n");
        InjectDefault3DModel();
    }

**Comment by theWatchmen** [comment]
Right, looks like you're not passing a glTF model to load in the command line. If you don't have glTF files already, there are instructions in the README (https://github.com/PacktPublishing/Mastering-Graphics-Programming-with-Vulkan#getting-the-code) to run the bootstrap script to download the glTF samples and the code above will work even if you don't pass the model as an argument to the program.

Let me know if this helps :)

**Comment by ohmaya** [comment]
It was changed on 20230211:
https://github.com/PacktPublishing/Mastering-Graphics-Programming-with-Vulkan/commit/0480bef1e4802fe11fe67d1fbe517f1dc5cdfed9#diff-55f1eabffd55a628477625c89a1b4d43f0383974598565a44a95faaa30b1907e

Previously it was an:
exit( -1 );

The issue was opened on 20230611, I now can't remember why I got the old code ...
