### ISSUE TITLE
No rule to make target 'chapter1'

### ISSUE THREAD

**Issue by BaronVerde** [PacktPublishing/Mastering-Graphics-Programming-with-Vulkan#44]
This is Debian Linux.

Targets RaptorFoundation and RaptorApp build just fine, chapter1 won't.

Unfortunately I am unfamiliar with the cmake file syntax.

**Comment by theWatchmen** [comment]
Could you provide the error that you get? Debian was the Linux system I tested on and last time I tried it was working fine.

**Comment by BernhardLThomas** [comment]
Heyo,
the issue seems to be one of case-sensitivity. The `chapter1` in the provided shell command should be `Chapter1`:
 
```bash
cmake --build build --target Chapter1 -- -j 4
```

At least that made it work for me.

**Comment by theWatchmen** [comment]
Ah yes, there is a typo in the book that we didn't catch until it was too late. The instruction in the README are correct. I will close this for now but feel free to re-open if you're still having issues.
