### ISSUE TITLE
Assets?

### ISSUE THREAD

**Issue by dgubser** [PacktPublishing/Mastering-Graphics-Programming-with-Vulkan#5]
Usage: chapter1 [path to glTF model]\n

Assets? or ???

**Comment by corporateshark** [comment]
https://github.com/PacktPublishing/Mastering-Graphics-Programming-with-Vulkan/pull/2

**Comment by dgubser** [comment]
Thank you Sergey.

**Comment by theWatchmen** [comment]
We have merged the #2 to make it easier to download the models and run the code :)
