### ISSUE TITLE
why can't I compile in my macOS? with Arm M3

### ISSUE THREAD

**Issue by the-code-samurai-97** [PacktPublishing/Mastering-Graphics-Programming-with-Vulkan#50]
i installed vulkan and which compiler should i use? gcc or clang?

**Comment by theWatchmen** [comment]
macOS is currently not supported as when we wrote the book some of the Vulkan features weren't available on that platform. We also don't have access to an Arm based Mac to test a different toolchain.

**Comment by the-code-samurai-97** [comment]
Thanks @theWatchmen I found a way to link Vulkan with Mac OS arm i, I am using Bazel to compile the code and I am using Imgui to visualize if I can convert this repo i will put a link for it later

**Comment by minggo** [comment]
Is it possible to use Parallel to install a windows or linux virtual machine to run the example?

**Comment by theWatchmen** [comment]
@minggo You can try, it all depends on what functionality gets exposed through the driver on the virtual machine.

**Comment by minggo** [comment]
@theWatchmen got it, thank you.
