### ISSUE TITLE
Wrong check in frag shader

### ISSUE THREAD

**Issue by valleymouth** [PacktPublishing/Mastering-Graphics-Programming-with-Vulkan#56]
https://github.com/PacktPublishing/Mastering-Graphics-Programming-with-Vulkan/blob/a03272b227a64a85a7b32b89ee5362671835f7d6/source/chapter2/shaders/main.frag#L139

Should be :
`if (textures.y != INVALID_TEXTURE_INDEX) { `

**Comment by theWatchmen** [comment]
Indeed, thanks for spotting this! I'll push a fix shortly :)

**Comment by valleymouth** [comment]
Awesome, learning a lot from the book btw :)
