### ISSUE TITLE
Running Project causes validation errors

### ISSUE THREAD

**Issue by Silver-will** [PacktPublishing/Mastering-Graphics-Programming-with-Vulkan#57]
Error as seen here:

```
MessageID: VUID-vkCreateCommandPool-queueFamilyIndex-01937 1457732636
Message: Validation Error: [ VUID-vkCreateCommandPool-queueFamilyIndex-01937 ] | MessageID = 0x56e33c1c | vkCreateCommandPool: pCreateInfo->queueFamilyIndex is VK_QUEUE_FAMILY_IGNORED, 
but it is required to provide a valid queue family index value. 
The Vulkan spec states: pCreateInfo->queueFamilyIndex must be the index of a queue family available in the logical device device 
(https://vulkan.lunarg.com/doc/view/1.3.261.1/windows/1.3-extensions/vkspec.html#VUID-vkCreateCommandPool-queueFamilyIndex-01937)
```

I imagine this might be due to my GPU not supporting something used in the code?

**Comment by theWatchmen** [comment]
Possibly. We fixed some of the queue handling code a while back but maybe we missed a corner case. Which GPU are you using?

**Comment by Silver-will** [comment]
@theWatchmen 
It's an intel(R) UHD integrated on an i3-1115G4

**Comment by theWatchmen** [comment]
It's an integrated graphics card which exposes only one queue. However I thought we had this case covered. Which line of code causes this error?

**Comment by theWatchmen** [comment]
Closing for lack of reply. Feel free to re-open if needed.
