### ISSUE TITLE
Question about vkCmdDrawMeshTasksIndirectCountNV 

### ISSUE THREAD

**Issue by omd24** [PacktPublishing/Mastering-Graphics-Programming-with-Vulkan#62]
For GPU culling and meshlet drawing, vkCmdDrawMeshTasksIndirectCountNV is used, but I don't see how the number of task shaders is specified. In the 'CullingEarly' pass, where the command buffer is written, the count buffer is calculated at the mesh level (so the maximum equals the number of meshes), but the task shaders should operate at the meshlet level, right? In other words, where do we define the number of task shaders to dispatch, considering vkCmdDrawMeshTasksIndirectCountNV seems to use the mesh count to specify the draw count?

**Comment by theWatchmen** [comment]
We do use the meshlet count, not the mesh count :) https://github.com/PacktPublishing/Mastering-Graphics-Programming-with-Vulkan/blob/main/source/chapter6/shaders/culling.glsl#L147C5-L147C79

In the culling shader, each thread processes a mesh instance and outputs the number or meshlets to process for that mesh. This value is then passed in the argument buffer for the indirect task shader invocation. Note that we divide by 32 because each task shader wave will process 32 meshlets in parallel.

Hope this helps, let me know if you have any further questions.

**Comment by omd24** [comment]
Oh, I see what I was missing! I was comparing the "direct" version (**vkCmdDrawMeshTasksNV**) versus the "indirect" version (**vkCmdDrawMeshTasksIndirectCountNV**) as explained on page 140. I thought the **task_count** provided in the direct version is the same as the "count" provided at the mesh level [on the cpu side](https://github.com/PacktPublishing/Mastering-Graphics-Programming-with-Vulkan/blob/eae09e0eef0ecaa680e27a03c7766413a4852236/source/chapter6/graphics/render_scene.cpp#L381).

I'm not very familiar with indirect drawing 😅 so just to be sure I understand this correctly:

In the indirect version, we specify the total draw count at the mesh level. But for each draw count, the number of tasks is specified in the argument buffer. The indirect dispatch will use that **taskCount** to dispatch that many tasks. 
Afterwards, in the task shader this we continue with dispatching **gl_TaskCountNV** mesh shaders for each task group, and ultimately ending with the corresponding pixel shader, right? Or am I still missing something?

**Comment by omd24** [comment]
One other related question regarding usage of "count buffer",  the documentation for **vkCmdDrawMeshTasksNV** says 

> the command will read an unsigned 32-bit integer from **countBuffer** located at **countBufferOffset** and use this as the draw count

Considering that the count buffer struct ([GpuMeshDrawCounts](https://github.com/PacktPublishing/Mastering-Graphics-Programming-with-Vulkan/blob/eae09e0eef0ecaa680e27a03c7766413a4852236/source/chapter6/graphics/render_scene.hpp#L374)) has several members but the call to **vkCmdDrawMeshTasksNV** specifies the count offest as 0, does this mean it will use first member **opaque_mesh_visible_count** [in the line I mentioned](https://github.com/PacktPublishing/Mastering-Graphics-Programming-with-Vulkan/blob/eae09e0eef0ecaa680e27a03c7766413a4852236/source/chapter6/graphics/render_scene.cpp#L381) ?

**Comment by omd24** [comment]
On an unrelated note, can you pls explain the purpose of  "Late" GBuffer Pass or "gbuffer_pass_late" ? I don't see that mentioned explicitly in the book.

**Comment by theWatchmen** [comment]
> In the indirect version, we specify the total draw count at the mesh level. But for each draw count, the number of tasks is specified in the argument buffer. The indirect dispatch will use that taskCount to dispatch that many tasks.
Afterwards, in the task shader this we continue with dispatching gl_TaskCountNV mesh shaders for each task group, and ultimately ending with the corresponding pixel shader, right? Or am I still missing something?

That's correct!

> Considering that the count buffer struct ([GpuMeshDrawCounts](https://github.com/PacktPublishing/Mastering-Graphics-Programming-with-Vulkan/blob/eae09e0eef0ecaa680e27a03c7766413a4852236/source/chapter6/graphics/render_scene.hpp#L374)) has several members but the call to vkCmdDrawMeshTasksNV specifies the count offest as 0, does this mean it will use first member opaque_mesh_visible_count [in the line I mentioned](https://github.com/PacktPublishing/Mastering-Graphics-Programming-with-Vulkan/blob/eae09e0eef0ecaa680e27a03c7766413a4852236/source/chapter6/graphics/render_scene.cpp#L381) ?

Correct again :) You can see [here](https://github.com/PacktPublishing/Mastering-Graphics-Programming-with-Vulkan/blob/eae09e0eef0ecaa680e27a03c7766413a4852236/source/chapter6/graphics/render_scene.cpp#L681) where we use `transparent_mesh_visible_count` instead.

> On an unrelated note, can you pls explain the purpose of "Late" GBuffer Pass or "gbuffer_pass_late" ? I don't see that mentioned explicitly in the book.

In chapter 6 we discuss a common algorithm for gpu culling that performs two passes: in the first pass (early) we render the geometry that we knew was visible in the previous frame and record any meshes that are rejected. We update the depth pyramid after this pass and perform a second pass (late) and render the meshes we rejected in the first pass to make sure they are rendered if they became visible in this frame.

**Comment by omd24** [comment]
Perfect. Thanks for the explanations <3
