### ISSUE TITLE
doesn't open

### ISSUE THREAD

**Issue by Dollengo** [PacktPublishing/Mastering-Graphics-Programming-with-Vulkan#63]
Arch Linux 6.11.5-arch1-1
shell: zsh

./Chapter15 ../../../deps/src/glTF-Sample-Models/2.0/WaterBottle/glTF/WaterBottle.gltf 
Memory Service Init
HeapAllocator of size 2147483648 created
WindowService init
Window created successfully
InputService init
Gpu Device init
GPU Used: AMD Radeon Vega 8 Graphics (RADV RAVEN)
/home/dollengo/Downloads/Mastering-Graphics-Programming-with-Vulkan/source/chapter15/graphics/gpu_device.cpp(536) : FALSE
zsh: trace trap (core dumped)  ./Chapter15

**Comment by theWatchmen** [comment]
Chapter 15 requires ray tracing, and from [this list](https://vulkan.gpuinfo.org/displayreport.php?id=33315#extensions) it looks like this device doesn't support it. Does the code work for earlier chapters?
