### ISSUE TITLE
Massive frame drop after a few minutes of running in chapters 1, 2, 3, 4 and 5 so far

### ISSUE THREAD

**Issue by dili-o** [PacktPublishing/Mastering-Graphics-Programming-with-Vulkan#66]
Hi,
I've been following the book for a few months now and noticed a persistent issue I run into in every chapter so far. After a few minutes running the application the total gpu frame time increases by about 5-6ms and there are consistent spikes of 30ms every 1 seconds for the rest of the application's runtime.
Here are my specs:

Processor | Intel(R) Core(TM) i5-9300HF CPU @ 2.40GHz

Video Card | NVIDIA GeForce GTX 1650

Operating System | Windows 11

RAM | 16 GB

VulkanSDK | 1.3.275.0

**Comment by dili-o** [comment]
Issue was with my gpu over heating.

**Comment by theWatchmen** [comment]
I was about to suggest the same, given the symptoms :)
