### ISSUE TITLE
Vulkan validation error on Linux (Ubuntu 22.04)

### ISSUE THREAD

**Issue by mslinklater** [PacktPublishing/Mastering-Graphics-Programming-with-Vulkan#8]
When running chapter 1 the following output occurs every frame:

 MessageID: VUID-vkGetPhysicalDeviceSurfaceFormatsKHR-surface-06211 1886124171
Message: Validation Error: [ VUID-vkGetPhysicalDeviceSurfaceFormatsKHR-surface-06211 ] Object 0: handle = 0x555555d8d4c0, type = VK_OBJECT_TYPE_PHYSICAL_DEVICE; | MessageID = 0x706bf88b | vkGetPhysicalDeviceSurfaceFormatsKHR(): surface is not supported by the physicalDevice. The Vulkan spec states: surface must be supported by physicalDevice, as reported by vkGetPhysicalDeviceSurfaceSupportKHR or an equivalent platform-specific mechanism (https://vulkan.lunarg.com/doc/view/1.3.239.0/linux/1.3-extensions/vkspec.html#VUID-vkGetPhysicalDeviceSurfaceFormatsKHR-surface-06211)

**Comment by theWatchmen** [comment]
Interesting, the surface creation should be handled by SDL. Could you provide more details about the system you are running on? GPU and driver version would be a good start.

**Comment by mslinklater** [comment]
Sure - I'm running on a laptop with both integrated and dedicated GPU - integrated is Intel UHD 630, dedicated is NVidia 1070. OS is PopOS 22.04LTS, which is a derivative of Ubuntu 22.04. X11 windowing system, 

I've included the output of 'vulkaninfo' for vulkan setup.

[vulkaninfo.zip](https://github.com/PacktPublishing/Mastering-Graphics-Programming-with-Vulkan/files/10777805/vulkaninfo.zip)

**Comment by theWatchmen** [comment]
I noticed this as well today. On Windows we have no leaks, so this must be something that is specific to Linux. I'll take a look.

**Comment by packt-irfaa** [comment]
Thank you @theWatchmen I am closing the issue.
