### ISSUE TITLE
Chapter 1 run error with gltf

### ISSUE THREAD

**Issue by BinBinMind** [PacktPublishing/Mastering-Graphics-Programming-with-Vulkan#9]
![image](https://user-images.githubusercontent.com/4458014/219536545-022ee765-8f48-4e0c-910f-62fdad7e3656.png)

**Comment by theWatchmen** [comment]
That warning is expected. By default the ImGui profiling window is too small, causing the error above. Once you expand it, the error will go away :)

**Comment by theWatchmen** [comment]
@BinBinMind did that solve the problem? Are you happy for us to close this issue?

**Comment by BinBinMind** [comment]
Yes,thanks a lot.The problem is solved
